name: Github sanity scanner

on:
  pull_request:
    branches: [ master ]

jobs:
  github-sanity-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    - name: Github sanity scanner
      uses: outscale/github-sanity-scan@main
      with:
        no-pull-request-target: true
